### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ghost** [rklaehn/radixtree#13]
Hey @rklaehn, would you mind to publish a new release with the cats 1.0 update?  As far as I'm concerned I'm just interested in Scala 2.12 :blush:

**Comment by rklaehn** [comment]
I will try to do this. I think I also have to release the dependency https://github.com/rklaehn/sonicreducer . Are the scala versions OK?

(really doing something completely different right now... )

**Comment by ghost** [comment]
@rklaehn Do you?  I wasn't aware of this dependency… as said, for me Scala 2.12 is sufficient.

**Comment by rklaehn** [comment]
https://github.com/rklaehn/radixtree/blob/master/build.sbt#L9

I get some weird scalajs build errors when trying to update the above dependency...

Not sure what happens if you publish a scala 2.12 lib that depends on a 2.11 lib. Probably nothing good.

**Comment by ghost** [comment]
But radixtree is already 2.12 isn't it?  I'm pretty sure that we use it with Scala 2.12 :smiley:

**Comment by rklaehn** [comment]
Hm, for some reason I am not able to publish to sonatype. Maybe my credentials have expired, or there is something broken with the build...

```
[error] (coreJVM / publishSigned) java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/rklaehn/radixtree_2.12/0.5.1/radixtree_2.12-0.5.1.pom.asc was refused by the server: Unauthorized
[error] (coreJS / publishSigned) java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/rklaehn/radixtree_sjs0.6_2.12/0.5.1/radixtree_sjs0.6_2.12-0.5.1.pom.asc was refused by the server: Unauthorized
```

will have to look into this, but not today...

**Comment by ghost** [comment]
Oh, I'm sorry for the troubles.  Perhaps try bintray?  In my experience it's way simpler to setup than Sonatype, and it gives you JCenter integration, so it's as good as sonatype as far as SBT is concerned.

**Comment by rklaehn** [comment]
I currently don't have time to look into this. I published radixtree_2.12-0.5.1 . Can you check if this works for you when using 2.12?

**Comment by ghost** [comment]
@rklaehn I tried in a larger project; compiled and passed tests, so seems to work as far as I can test.

**Comment by rklaehn** [comment]
OK, cool. Will close this then. Would appreciate if somebody could monernize the sbt built though. I think at this point it would be fine to just rip out the scalajs stuff....

**Comment by ghost** [comment]
@rklaehn  I can do that, although I'd definitely throw away the scalajs stuff: We don't use scalajs, nor do I have any experience with it, so don't want to spend any time on it.

But how about the release workflow?  Currently you release to Maven Central directly and manually, don't you?  How about automating releases via Travis CI?  And perhaps use Bintray instead of Sonatype?  In my experience Bintray is easier to setup and maintain, because it's self-serviced and doesn't require roundtrips with Sonatype's support.

**Comment by ghost** [comment]
@rklaehn ping :slightly_smiling_face:
